name: Testing Pipeline

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          mkdir -p ~/.aws
          echo -e "[default]\naws_access_key_id=AKAI12345\naws_secret_access_key=S12345678" > ~/.aws/credentials
      - run: uv sync --all-extras --dev
      - name: Code linting
        run: uv run ruff check --exit-zero

      - name: Run unit tests
        run: uv run pytest
